image: maven:latest

before_script:
  #SSH agent
  - 'which ssh-agent || ( apk update  && apk add openssh)'
  - eval $(ssh-agent -s)    
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  #GPG (gnupg)
  - 'which gpg-agent || ( apk update  && apk add gnupg)'
  - gpg -v --batch --import <(echo "$GPG_PRIVATE_KEY")
  # Install JFrog CLI / configure artifactory
  -  curl -fL https://getcli.jfrog.io | sh
  - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
  - ./jfrog rt c show
  - export M2_HOME=/usr/share/maven
  - sed -i 's,SNAPSHOT_REPO_KEY,'"$SNAPSHOT_REPO_KEY"',g' configuration.yml
  - sed -i 's,RELEASE_REPO_KEY,'"$RELEASE_REPO_KEY"',g' configuration.yml
  - sed -i 's,ARTIFACTORY_JCENTER_REPO_KEY,'"$ARTIFACTORY_JCENTER_REPO_KEY"',g' configuration.yml
  # CPLEX JAR
  - mkdir -p ~/CPLEX/lib/
  - export CPLEX_HOME=~CPLEX
  - ./jfrog rt dl --flat true libs-release-local/com/ibm/ilog/cplex/1.2.5/cplex-1.2.5.jar $CPLEX_HOME/lib/cplex.jar

stages:
 - compile
 - test
 - deploy
 
maven_compile:
  stage: compile
  tags:
    - maven
  script:
    - mvn compile
 
maven test:
  stage: test
  tags: 
    - maven
  script:
    - mvn test

maven_deploy:
  stage: deploy
  tags:
    - maven
    - artifactory
  script:
    - ./jfrog rt mvn "clean verify gpg:sign install -DadditionalJOption=-Xdoclint:none" configuration.yml --build-name=solvers-cplex_gitlabci_build --build-number=$CI_JOB_ID
    - ./jfrog rt bce solvers-cplex_gitlabci_build $CI_JOB_ID
    - ./jfrog rt bp solvers-cplex_gitlabci_build $CI_JOB_ID
#  only:
#    - master