language: java
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/lib


before_install:
  - wget https://drive.google.com/file/d/${CPLEX_SHARE_FILE}
  - mv ${CPLEX_SHARE_FILE} $HOME/lib/cplex.jar

deploy:
    provider: script
    script:
        - build/deploy.sh $TRAVIS_BRANCH
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^dev|master$
