language: java
cache:
  directories:
    - $HOME/.gradle/caches/

before_instal:
    - sudo apt-get install -qq sshpass

install: echo "skip install"

script: echo "not testing"

deploy:
    provider: script
    script:
        - build/deploy.sh $TRAVIS_BRANCH
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^dev|master$
